Bevy 0.15
malbernaz/bevy_lit pull request #8
Opened 2024-12-03 13:12 UTC by csandven

2024-12-08 12:29 UTC, csandven commented
@malbernaz  Ant chance for a review and potential crate publishing?

2024-12-09 11:49 UTC, malbernaz commented
> @malbernaz Any chance for a review and potential crate publishing?

Absolutely! I'll check it out. Thanks for this :)

2024-12-09 22:41 UTC, malbernaz reviewed
Overall this is looking really good, thanks a lot!

I need to test this more thoroughly for `webgpu`  and `webgl` targets. Once it's done we can merge and publish it.

Also can you run `cargo fmt` on the files that were modified?

2024-12-09 22:41 UTC, malbernaz commented on src/extract.rs
>      commands.spawn(ExtractedLightOccluder2d::default());
This is adding an empty `ExtractedLightOccluder2d` that is not needed any more. In fact if you run the example you'll find an artifact in the middle of the screen that is a ghost occluder. The loop in `sdf.wgsl:27` as it is accounts for this empty element and starts at element `2u` (I cannot recall why 2). It should start from `0u` from now on.

My bad that this is poorly commented. It's related to how GPU buffers are created in bevy.

2024-12-09 22:41 UTC, malbernaz commented on src/extract.rs
>      commands.spawn(ExtractedPointLight2d::default());
This is also adding an empty entity that should also be removed from `lighting.wgsl:42`.

2024-12-09 22:41 UTC, malbernaz commented on Cargo.toml
> +bevy_image = "0.15.0"
We can solve it by adding `png` to the bevy features. Can you do this and add a todo comment saying that we should revisit it after the bevy issue is solved.

2024-12-09 22:41 UTC, malbernaz commented on src/types.rs
> +#[deprecated]
```rust
#[deprecated(
    since = "0.4.0",
    note = "Use the `PointLight2d` component instead."
)]
```

2024-12-09 22:41 UTC, malbernaz commented on src/types.rs
> +#[deprecated]
```rust
#[deprecated(
    since = "0.4.0",
    note = "Use the `LightOccluder2d` component instead."
)]
```

2024-12-09 22:41 UTC, malbernaz commented on examples/basic.rs
> +                ..Default::default()
`..default()` instead for consistency.

2024-12-09 22:41 UTC, malbernaz commented on examples/basic.rs
> +        Camera2d::default(),
We can drop the `::default()` here.

2024-12-10 14:37 UTC, csandven commented
Thanks for the comments. Added fixes now. Also added a rustfmt.toml as the one I have for work i really different than what is used normally. Hope it is fine!

2024-12-10 15:09 UTC, malbernaz requested changes
The only two changes I requested are to make everything work correctly on web targets.

The context is that `GpuArrayBuffer` is probably initialising the array buffers with an empty value - I have to check bevy's source to understand exactly what has changed since `0.14`. This behaviour creates an empty point light and an empty occluder that was visible on the screen.

Thanks a lot for the contribution! After merged I'll increment the changelog and publish the update. 👏👏👏

2024-12-10 15:20 UTC, merged

2024-12-10 15:42 UTC, malbernaz commented
Released! Thanks ❤️